name: Foothills Philharmonic Society
markdown: redcarpet
url: http://www.foothillsphilharmonic.com
permalink: /:categories/:year/:month/:day/:title
post_dirs: true

defaults:
  -
    scope:
      path: ""
    values:
      description: "Foothills Philharmonic Society - Bringing beautiful music to the Foothills in Southern Alberta, Canada"
      image: "/images/default-fps-image.jpg"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
