name: Foothills Philharmonic Society
markdown: redcarpet
url: http://www.foothillsphilharmonic.com

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      description: "Foothills Philharmonic Society - Bringing beautiful music to the Foothills in Southern Alberta, Canada"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
